--- #YAML:1.0
name:               File-Path-Tiny
version:            0.3
abstract:           recursive versions of mkdir() and rmdir() without as much overhead as File::Path
author:
    - Daniel Muey <http://drmuey.com/cpan_contact.pl>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
